<?php

$work = new Cuztom_post_type('Spectacles', [
    'menu_position' => 1,
    'menu_icon' => 'dashicons-tickets-alt',
]);

$work->add_meta_box(
    'cuztom-spectacles',
    'Spectacles',

    array(
        array(
            'id' => '_titre',
            'type' => 'text',
            'label' => 'Titre',
            'description' => 'Ajouter une titre',
            'explanation'           => __('Ce texte apparaîtra sous l\'image. Les majuscules seront gérées automatiquement.'),
            'default_value'         => '',
            'options'               => array(),
            'args'                  => array(),
            'repeatable'            => false,
            'show_admin_column'     => false,
            'admin_column_sortable' => false,
            'admin_column_filter'   => false,
        ),
        array(
            'id' => '_author',
            'type' => 'text',
            'label' => 'Autheur',
            'description' => 'Ajouter un autheur',
            'explanation'           => __('Ce texte apparaîtra sous le titre. Les majuscules seront gérées automatiquement.'),
            'default_value'         => '',
            'options'               => array(),
            'args'                  => array(),
            'repeatable'            => false,
            'show_admin_column'     => false,
            'admin_column_sortable' => false,
            'admin_column_filter'   => false,
        ),
        array(
            'id' => '_lien',
            'type' => 'text',
            'label' => 'Lien',
            'description' => 'Ajouter un lien',
            'explanation'           => __('Ici le lien de redirection. Pas de lien nécessaire si c\'est non cliquable.'),
            'default_value'         => '',
            'options'               => array(),
            'args'                  => array(),
            'repeatable'            => false,
            'show_admin_column'     => false,
            'admin_column_sortable' => false,
            'admin_column_filter'   => false,
        ),
        array(
            'id' => '_date',
            'type' => 'text',
            'label' => 'Date',
            'description' => 'Ajouter une date',
            'explanation'           => __('Ici la date du spectacle / exposition. Sept caractères maximum.'),
            'default_value'         => '',
            'options'               => array(),
            'args'                  => array(),
            'repeatable'            => false,
            'show_admin_column'     => false,
            'admin_column_sortable' => false,
            'admin_column_filter'   => false,
        ),
        array(
            'id' => '_date2',
            'type' => 'text',
            'label' => 'Seconde date',
            'description' => 'Ajouter une seconde date',
            'explanation'           => __('Ici la seconde date du spectacle / exposition. Sept caractères maximum.'),
            'placeholder'           => 'S',
            'options'               => array(),
            'args'                  => array(),
            'repeatable'            => false,
            'show_admin_column'     => false,
            'admin_column_sortable' => false,
            'admin_column_filter'   => false,
        ),
        array(
            'id' => '_image',
            'label' => 'Image',
            'type' => 'image',
            'description' => 'Importer une image'
        ),
    ));
